name: Prettier
on:
    pull_request:
    push:
        branches:
            - main

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '18.x'

            - name: Install dependencies
              run: npm install

            - name: Run Prettier
              run: npm run format

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4.1.2
              with:
                  commit_message: Apply formatting changes
                  branch: ${{ github.head_ref }}
